# Generated by Django 2.2.4 on 2019-09-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_id', models.SlugField(blank=True, max_length=6, primary_key=True, serialize=False)),
                ('short_url', models.URLField(max_length=250)),
                ('long_url', models.URLField(max_length=250)),
            ],
            options={
                'verbose_name': 'Url',
                'verbose_name_plural': 'Urls',
            },
        ),
    ]
